languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
title = "Zodiac"

[params]
  displayName = "简体中文"
  isoCode = "cn"
  rtl = false
  dateFormat = "2006 年 1 月 2 日"
  logo = "img/site_logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "KeJi's Zodiac"
  copyright = '© 2024 - { year } KeJi All Rights Reserved.'

[params.author]
  name = "KeJi"
  #image = "img/avatar.png"
  headline = "notes, knowledge and ideas"
  #bio = "Everyone is mania in general"
