[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 30


[[main]]
  name = "Knowledge"
  pageRef = "/knowledge"
  weight = 30

[[main]]
  name = "Ideas"
  pageRef = "/idea"
  weight = 30